# Generated by Django 4.1.6 on 2023-02-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
